import { CommonModule } from '@angular/common';
import { ModuleWithProviders, NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { AntModule, NebularModule, PrimeModule, NgxModule } from './modules';
import {
  CategorySelectComponent,
  CustomerSelectComponent,
  EmployeeSelectComponent,
  EmployeeItemComponent,
  EmployeeFilterComponent,
  PipelineSelectComponent,
  ProductSelectComponent,
  DealItemComponent,
  TicketItemComponent,
  CustomerItemComponent,
  CustomerImportItemComponent,
  SelectDateComponent,
  SelectDateTimeComponent,
} from './components';
import {
  CustomerSavePage,
  EmployeeSavePage,
  ProductSavePage,
  PipelineMovetoPage,
  CustomerImportPage,
  EmployeeImportPage,
  ImportDataPage,
  ProductImportPage,
  MailSenderPage,
  CustomerProfilePage,
  SettingPasswordPage,
  SettingProfilePage,
  SettingRolePage,
  EventSavePage,
} from './pages';
import {
  ActivityAddComponent,
  ActivityCalendarArea,
  ActivityCalendarItemComponent,
  ActivityCardArea,
  ActivityCardItemComponent,
  ActivityDatatableArea,
  ActivityDatatableItemComponent,
  ActivityExportComponent,
  ActivityMainContainer,
  ActivityQueryComponent,
  ActivityPaginationComponent,
  ActivityTypeComponent,
  ActivitySaveModal,
  ActivitySolveCheckComponent,
  ActivityPageCountComponent,
} from './features/activity';
import {
  DealAddComponent,
  DealKanbanArea,
  DealKanbanItemComponent,
  DealCardArea,
  DealCardItemComponent,
  DealDatatableArea,
  DealDatatableItemComponent,
  DealExportComponent,
  DealMainContainer,
  DealQueryComponent,
  DealPaginationComponent,
  DealTypeComponent,
  DealProcessComponent,
  DealSaveModal,
  DealSelect1Component,
  DealKanbanSubItemComponent,
  DealPageCountComponent,
  DealSolveCheckComponent
} from './features/deal';
import {
  NoteAddComponent,
  NoteCardArea,
  NoteCardItemComponent,
  NoteDatatableArea,
  NoteDatatableItemComponent,
  NoteExportComponent,
  NoteMainContainer,
  NoteQueryComponent,
  NotePaginationComponent,
  NoteSaveModal,
  NotePageCountComponent,
  NoteSolveCheckComponent
} from './features/note';
import {
  LogCardArea,
  LogCardItemComponent,
  LogDatatableArea,
  LogDatatableItemComponent,
  LogExportComponent,
  LogMainContainer,
  LogTypeComponent,
  LogPageCountComponent,
  LogSolveCheckComponent,
  LogPaginationComponent
} from './features/log';
import {
  CampaignAddComponent,
  CampaignCardArea,
  CampaignCardItemComponent,
  CampaignDatatableArea,
  CampaignDatatableItemComponent,
  CampaignExportComponent,
  CampaignMainContainer,
  CampaignQueryComponent,
  CampaignPaginationComponent,
  CampaignTypeComponent,
  CampaignSaveModal,
  CampaignSelect1Component,
  CampaignSolveCheckComponent,
  CampaignPageCountComponent,
  CampaignInformationComponent
} from './features/campaign';
import {
  PipelineAddComponent,
  PipelineCardArea,
  PipelineCardItemComponent,
  PipelineDatatableArea,
  PipelineDatatableItemComponent,
  PipelineExportComponent,
  PipelineMainContainer,
  PipelineQueryComponent,
  PipelinePaginationComponent,
  PipelineTypeComponent,
  PipelineSaveModal,
  PipelineSelect1Component,
  PipelinePageCountComponent
} from './features/pipeline';
import {
  AttachmentAddComponent,
  AttachmentCardArea,
  AttachmentCardItemComponent,
  AttachmentDatatableArea,
  AttachmentDatatableItemComponent,
  AttachmentExportComponent,
  AttachmentMainContainer,
  AttachmentQueryComponent,
  AttachmentPaginationComponent,
  AttachmentTypeComponent,
  AttachmentSaveModal,
  SizePipe,
  AttachmentPageCountComponent,
  AttachmentSolveCheckComponent
} from './features/attachment';
import {
  CustomerAddComponent,
  CustomerCardArea,
  CustomerCardItemComponent,
  CustomerDatatableArea,
  CustomerDatatableItemComponent,
  CustomerExportComponent,
  CustomerMainContainer,
  CustomerQueryComponent,
  CustomerPaginationComponent,
  CustomerTypeComponent,
  CustomerSaveModal,
  CustomerImportComponent,
  CustomerSelect1Component,
  CustomerSolveCheckComponent,
  CustomerPageCountComponent,
} from './features/customer';
import {
  ProductAddComponent,
  ProductCardArea,
  ProductCardItemComponent,
  ProductDatatableArea,
  ProductDatatableItemComponent,
  ProductExportComponent,
  ProductMainContainer,
  ProductQueryComponent,
  ProductPaginationComponent,
  ProductTypeComponent,
  ProductSaveModal,
  ProductImportComponent,
  ProductSelect1Component,
  ProductSolveCheckComponent,
  ProductPageCountComponent,
  ProductCategoryComponent
} from './features/product';
import {
  CategoryAddComponent,
  CategoryCardArea,
  CategoryCardItemComponent,
  CategoryDatatableArea,
  CategoryDatatableItemComponent,
  CategoryExportComponent,
  CategoryMainContainer,
  CategoryQueryComponent,
  CategoryPaginationComponent,
  CategoryTypeComponent,
  CategorySaveModal,
  CategorySelect1Component,
  CategorySolveCheckComponent,
  CategoryPageCountComponent,
  CategoryProductComponent
} from './features/category';
import {
  EmployeeAddComponent,
  EmployeeCardArea,
  EmployeeCardItemComponent,
  EmployeeDatatableArea,
  EmployeeDatatableItemComponent,
  EmployeeExportComponent,
  EmployeeMainContainer,
  EmployeeQueryComponent,
  EmployeePaginationComponent,
  EmployeeTypeComponent,
  EmployeeSaveModal,
  EmployeeSelect1Component,
  EmployeeSolveCheckComponent,
  EmployeePageCountComponent
} from './features/employee';
import { LengthPipe, ShortPipe, TimePipe, MoneyPipe, TotalMoneyPipe, MaskPipe, SeparatorPipe, KeyPipe } from './pipes';
import { DragDropModule } from '@angular/cdk/drag-drop';
import { ClipboardModule } from '@angular/cdk/clipboard';
import { adapterFactory } from 'angular-calendar/date-adapters/date-fns';
import { CalendarModule, DateAdapter } from 'angular-calendar';
export const EXTRA_MODULES = [
  AntModule,
  NebularModule,
  PrimeModule,
  NgxModule,

];

export const ANGULAR_MODULES = [
  FormsModule,
  ReactiveFormsModule,
  CommonModule,
  DragDropModule,
  ClipboardModule
];
export const FEATURES = [
  ProductAddComponent,
  ProductCardArea,
  ProductCardItemComponent,
  ProductDatatableArea,
  ProductDatatableItemComponent,
  ProductExportComponent,
  ProductMainContainer,
  ProductQueryComponent,
  ProductPaginationComponent,
  ProductTypeComponent,
  ProductSaveModal,
  ProductImportComponent,
  ProductSelect1Component,
  ProductSolveCheckComponent,
  ProductPageCountComponent,
  ProductCategoryComponent,

  CategoryAddComponent,
  CategoryCardArea,
  CategoryCardItemComponent,
  CategoryDatatableArea,
  CategoryDatatableItemComponent,
  CategoryExportComponent,
  CategoryMainContainer,
  CategoryQueryComponent,
  CategoryPaginationComponent,
  CategoryTypeComponent,
  CategorySaveModal,
  CategorySelect1Component,
  CategorySolveCheckComponent,
  CategoryPageCountComponent,
  CategoryProductComponent,

  EmployeeAddComponent,
  EmployeeCardArea,
  EmployeeCardItemComponent,
  EmployeeDatatableArea,
  EmployeeDatatableItemComponent,
  EmployeeExportComponent,
  EmployeeMainContainer,
  EmployeeQueryComponent,
  EmployeePaginationComponent,
  EmployeeTypeComponent,
  EmployeeSaveModal,
  EmployeeSelect1Component,
  EmployeeSolveCheckComponent,
  EmployeePageCountComponent,

  CustomerAddComponent,
  CustomerCardArea,
  CustomerCardItemComponent,
  CustomerDatatableArea,
  CustomerDatatableItemComponent,
  CustomerExportComponent,
  CustomerMainContainer,
  CustomerQueryComponent,
  CustomerPaginationComponent,
  CustomerTypeComponent,
  CustomerSaveModal,
  CustomerImportComponent,
  CustomerSelect1Component,
  CustomerSolveCheckComponent,
  CustomerPageCountComponent,

  LogCardArea,
  LogCardItemComponent,
  LogDatatableArea,
  LogDatatableItemComponent,
  LogExportComponent,
  LogMainContainer,
  LogTypeComponent,
  LogPageCountComponent,
  LogSolveCheckComponent,
  LogPaginationComponent,

  NoteAddComponent,
  NoteCardArea,
  NoteCardItemComponent,
  NoteDatatableArea,
  NoteDatatableItemComponent,
  NoteExportComponent,
  NoteMainContainer,
  NoteQueryComponent,
  NotePaginationComponent,
  NoteSaveModal,
  NotePageCountComponent,
  NoteSolveCheckComponent,

  CampaignAddComponent,
  CampaignCardArea,
  CampaignCardItemComponent,
  CampaignDatatableArea,
  CampaignDatatableItemComponent,
  CampaignExportComponent,
  CampaignMainContainer,
  CampaignQueryComponent,
  CampaignPaginationComponent,
  CampaignTypeComponent,
  CampaignSaveModal,
  CampaignSelect1Component,
  CampaignSolveCheckComponent,
  CampaignPageCountComponent,
  CampaignInformationComponent,

  ActivityAddComponent,
  ActivityCalendarArea,
  ActivityCalendarItemComponent,
  ActivityCardArea,
  ActivityCardItemComponent,
  ActivityDatatableArea,
  ActivityDatatableItemComponent,
  ActivityExportComponent,
  ActivityMainContainer,
  ActivityQueryComponent,
  ActivityPaginationComponent,
  ActivityTypeComponent,
  ActivitySaveModal,
  ActivitySolveCheckComponent,
  ActivityPageCountComponent,

  DealAddComponent,
  DealKanbanArea,
  DealKanbanItemComponent,
  DealCardArea,
  DealCardItemComponent,
  DealDatatableArea,
  DealDatatableItemComponent,
  DealExportComponent,
  DealMainContainer,
  DealProcessComponent,
  DealQueryComponent,
  DealPaginationComponent,
  DealTypeComponent,
  DealKanbanSubItemComponent,
  DealSaveModal,
  DealSelect1Component,
  DealPageCountComponent,
  DealSolveCheckComponent,

  AttachmentAddComponent,
  AttachmentCardArea,
  AttachmentCardItemComponent,
  AttachmentDatatableArea,
  AttachmentDatatableItemComponent,
  AttachmentExportComponent,
  AttachmentMainContainer,
  AttachmentQueryComponent,
  AttachmentPaginationComponent,
  AttachmentTypeComponent,
  AttachmentPageCountComponent,
  AttachmentSolveCheckComponent,
  AttachmentSaveModal,
  SizePipe,

  PipelineAddComponent,
  PipelineCardArea,
  PipelineCardItemComponent,
  PipelineDatatableArea,
  PipelineDatatableItemComponent,
  PipelineExportComponent,
  PipelineMainContainer,
  PipelineQueryComponent,
  PipelinePaginationComponent,
  PipelineTypeComponent,
  PipelineSaveModal,
  PipelineSelect1Component,
  PipelinePageCountComponent
];
export const REUSE_COMPONENTS = [
  CategorySelectComponent,
  CustomerSelectComponent,
  EmployeeSelectComponent,
  EmployeeItemComponent,
  EmployeeFilterComponent,
  PipelineSelectComponent,
  ProductSelectComponent,
  DealItemComponent,
  TicketItemComponent,
  CustomerItemComponent,
  CustomerImportItemComponent,
  SelectDateComponent,
  SelectDateTimeComponent,
];

export const REUSE_PAGES = [
  CustomerSavePage,
  EmployeeSavePage,
  ProductSavePage,
  PipelineMovetoPage,
  CustomerImportPage,
  EmployeeImportPage,
  ImportDataPage,
  ProductImportPage,
  MailSenderPage,
  CustomerProfilePage,
  SettingPasswordPage,
  SettingProfilePage,
  EventSavePage,
  SettingRolePage,
];
export const PIPES = [
  LengthPipe,
  ShortPipe,
  TimePipe,
  MoneyPipe,
  TotalMoneyPipe,
  MaskPipe,
  SeparatorPipe,
  KeyPipe
];
@NgModule({
  imports: [
    ...ANGULAR_MODULES,
    ...EXTRA_MODULES,
    CalendarModule.forRoot({
      provide: DateAdapter,
      useFactory: adapterFactory,
    }),
  ],
  declarations: [
    ...REUSE_COMPONENTS,
    ...REUSE_PAGES,
    ...FEATURES,
    ...PIPES
  ],
  exports: [
    ...ANGULAR_MODULES,
    ...EXTRA_MODULES,
    ...FEATURES,
    ...REUSE_COMPONENTS,
    ...REUSE_PAGES,
    ...PIPES,
  ],
})
export class ExtrasModule {
  static forRoot(name: string = 'default'): ModuleWithProviders<ExtrasModule> {
    return {
      ngModule: ExtrasModule,
      providers: [
        ...NebularModule.forRoot().providers,
        ...NgxModule.forRoot().providers,
      ]
    };
  }
  static forChild(name: string = 'default'): ModuleWithProviders<ExtrasModule> {
    return {
      ngModule: ExtrasModule,
      providers: [
        ...NebularModule.forChild().providers,
        ...NgxModule.forChild().providers,
      ]
    };
  }
}
