steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build', '--prod']
- name: 'gcr.io/$_FIREBASE_TOKEN/firebase'
  args: ['deploy', '--only', 'hosting']
