import { AccountVM } from '@view-models';

export interface RoleVM {
  readonly id: string;
  readonly name: string;
  readonly notChange: boolean;
  readonly level: number;
  readonly canAccessEmployee: boolean;
  readonly canCreateEmployee: boolean;
  readonly canUpdateEmployee: boolean;
  readonly canRemoveEmployee: boolean;
  readonly canImportEmployee: boolean;
  readonly canExportEmployee: boolean;
  readonly canCreateLead: boolean;
  readonly canUpdateLead: boolean;
  readonly canRemoveLead: boolean;
  readonly canImportLead: boolean;
  readonly canExportLead: boolean;
  readonly canAccessDeal: boolean;
  readonly canCreateDeal: boolean;
  readonly canUpdateDeal: boolean;
  readonly canRemoveDeal: boolean;
  readonly canImportDeal: boolean;
  readonly canExportDeal: boolean;
  readonly canAccessProcess: boolean;
  readonly canCreateProcess: boolean;
  readonly canUpdateProcess: boolean;
  readonly canRemoveProcess: boolean;
  readonly canImportProcess: boolean;
  readonly canExportProcess: boolean;
  readonly canAccessRole: boolean;
  readonly canCreateRole: boolean;
  readonly canUpdateRole: boolean;
  readonly canRemoveRole: boolean;
  readonly canImportRole: boolean;
  readonly canExportRole: boolean;
  readonly canAccessCustomer: boolean;
  readonly canCreateCustomer: boolean;
  readonly canUpdateCustomer: boolean;
  readonly canRemoveCustomer: boolean;
  readonly canImportCustomer: boolean;
  readonly canExportCustomer: boolean;
  readonly canAccessActivity: boolean;
  readonly canCreateActivity: boolean;
  readonly canUpdateActivity: boolean;
  readonly canRemoveActivity: boolean;
  readonly canImportActivity: boolean;
  readonly canExportActivity: boolean;
  readonly canAccessTicket: boolean;
  readonly canCreateTicket: boolean;
  readonly canUpdateTicket: boolean;
  readonly canRemoveTicket: boolean;
  readonly canImportTicket: boolean;
  readonly canExportTicket: boolean;
  readonly canAccessProduct: boolean;
  readonly canCreateProduct: boolean;
  readonly canUpdateProduct: boolean;
  readonly canRemoveProduct: boolean;
  readonly canImportProduct: boolean;
  readonly canExportProduct: boolean;
  readonly canAccessEvent: boolean;
  readonly canCreateEvent: boolean;
  readonly canUpdateEvent: boolean;
  readonly canRemoveEvent: boolean;
  readonly canImportEvent: boolean;
  readonly canExportEvent: boolean;
  readonly canAccessFeedback: boolean;
  readonly canCreateFeedback: boolean;
  readonly canUpdateFeedback: boolean;
  readonly canRemoveFeedback: boolean;
  readonly canImportFeedback: boolean;
  readonly canExportFeedback: boolean;
  readonly description: string;
  readonly accounts: AccountVM[];
  readonly isDelete: boolean;
  readonly createdBy: string;
  readonly updatedBy: string;
  readonly createdAt: Date;
  readonly updatedAt: Date;
}

export interface RoleCM {
  name: string;
  notChange: boolean;
  level: number;
  canAccessEmployee: boolean;
  canCreateEmployee: boolean;
  canUpdateEmployee: boolean;
  canRemoveEmployee: boolean;
  canImportEmployee: boolean;
  canExportEmployee: boolean;
  canCreateLead: boolean;
  canUpdateLead: boolean;
  canRemoveLead: boolean;
  canImportLead: boolean;
  canExportLead: boolean;
  canAccessDeal: boolean;
  canCreateDeal: boolean;
  canUpdateDeal: boolean;
  canRemoveDeal: boolean;
  canImportDeal: boolean;
  canExportDeal: boolean;
  canAccessProcess: boolean;
  canCreateProcess: boolean;
  canUpdateProcess: boolean;
  canRemoveProcess: boolean;
  canImportProcess: boolean;
  canExportProcess: boolean;
  canAccessRole: boolean;
  canCreateRole: boolean;
  canUpdateRole: boolean;
  canRemoveRole: boolean;
  canImportRole: boolean;
  canExportRole: boolean;
  canAccessCustomer: boolean;
  canCreateCustomer: boolean;
  canUpdateCustomer: boolean;
  canRemoveCustomer: boolean;
  canImportCustomer: boolean;
  canExportCustomer: boolean;
  canAccessActivity: boolean;
  canCreateActivity: boolean;
  canUpdateActivity: boolean;
  canRemoveActivity: boolean;
  canImportActivity: boolean;
  canExportActivity: boolean;
  canAccessTicket: boolean;
  canCreateTicket: boolean;
  canUpdateTicket: boolean;
  canRemoveTicket: boolean;
  canImportTicket: boolean;
  canExportTicket: boolean;
  canAccessProduct: boolean;
  canCreateProduct: boolean;
  canUpdateProduct: boolean;
  canRemoveProduct: boolean;
  canImportProduct: boolean;
  canExportProduct: boolean;
  canAccessEvent: boolean;
  canCreateEvent: boolean;
  canUpdateEvent: boolean;
  canRemoveEvent: boolean;
  canImportEvent: boolean;
  canExportEvent: boolean;
  canAccessFeedback: boolean;
  canCreateFeedback: boolean;
  canUpdateFeedback: boolean;
  canRemoveFeedback: boolean;
  canImportFeedback: boolean;
  canExportFeedback: boolean;
  description: string;
}

export interface RoleUM {
  id: string;
  name: string;
  notChange: boolean;
  level: number;
  canAccessEmployee: boolean;
  canCreateEmployee: boolean;
  canUpdateEmployee: boolean;
  canRemoveEmployee: boolean;
  canImportEmployee: boolean;
  canExportEmployee: boolean;
  canCreateLead: boolean;
  canUpdateLead: boolean;
  canRemoveLead: boolean;
  canImportLead: boolean;
  canExportLead: boolean;
  canAccessDeal: boolean;
  canCreateDeal: boolean;
  canUpdateDeal: boolean;
  canRemoveDeal: boolean;
  canImportDeal: boolean;
  canExportDeal: boolean;
  canAccessProcess: boolean;
  canCreateProcess: boolean;
  canUpdateProcess: boolean;
  canRemoveProcess: boolean;
  canImportProcess: boolean;
  canExportProcess: boolean;
  canAccessRole: boolean;
  canCreateRole: boolean;
  canUpdateRole: boolean;
  canRemoveRole: boolean;
  canImportRole: boolean;
  canExportRole: boolean;
  canAccessCustomer: boolean;
  canCreateCustomer: boolean;
  canUpdateCustomer: boolean;
  canRemoveCustomer: boolean;
  canImportCustomer: boolean;
  canExportCustomer: boolean;
  canAccessActivity: boolean;
  canCreateActivity: boolean;
  canUpdateActivity: boolean;
  canRemoveActivity: boolean;
  canImportActivity: boolean;
  canExportActivity: boolean;
  canAccessTicket: boolean;
  canCreateTicket: boolean;
  canUpdateTicket: boolean;
  canRemoveTicket: boolean;
  canImportTicket: boolean;
  canExportTicket: boolean;
  canAccessProduct: boolean;
  canCreateProduct: boolean;
  canUpdateProduct: boolean;
  canRemoveProduct: boolean;
  canImportProduct: boolean;
  canExportProduct: boolean;
  canAccessEvent: boolean;
  canCreateEvent: boolean;
  canUpdateEvent: boolean;
  canRemoveEvent: boolean;
  canImportEvent: boolean;
  canExportEvent: boolean;
  canAccessFeedback: boolean;
  canCreateFeedback: boolean;
  canUpdateFeedback: boolean;
  canRemoveFeedback: boolean;
  canImportFeedback: boolean;
  canExportFeedback: boolean;
  description: string;
}
